### ISSUE TITLE
XIAO_ESP32C6 "Received NACK on transmit of address"

### ISSUE THREAD

**Issue by hunterpitts** [Sensirion/arduino-i2c-sts4x#2]
Hello,

I am using a XIAO_ESP32C6 with the STS40-CD1B-R3 temperature sensor. When I connect the temperature sensor to an ardiuno uno, the sensor works perfect. After connecting the XIAO_ESP32C6, "Error trying to execute measureHighPrecision(): Received NACK on transmit of address"

Any help would be greatly appreciated.

**Comment by LeonieFierz** [comment]
Hi @hunterpitts 
thanks for contacting us. As the communication does not work, it could be interchanged SDA/SCL lines. Further, did you already check the pull up resistor configuration?
Best, Léonie

**Comment by hunterpitts** [comment]
I checked both and no success.

**Comment by hunterpitts** [comment]
I have fixed the issue. The SCL / SDA lines were not working because the board connections were faulty.

**Comment by LeonieFierz** [comment]
Perfect, thank you for letting us know it worked out now.
